//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySiteDataEntities : DbContext
    {
        public MySiteDataEntities()
            : base("name=MySiteDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<SelectProjectGroup> SelectProjectGroup { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectGroups> ProjectGroups { get; set; }
        public virtual DbSet<Seo> Seo { get; set; }
    }
}
