//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySite.Models.Model
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    [MetadataType(typeof(ProjectGroupsMetadata))]
    public partial class ProjectGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectGroups()
        {
            this.SelectProjectGroup = new HashSet<SelectProjectGroup>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string GroupImage { get; set; }
        public string GroupDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectProjectGroup> SelectProjectGroup { get; set; }
    }
}
